config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "installation-climatisation", to: "pages#installation"
  get "maintenance-nettoyage-climatisation", to: "pages#maintenance_nettoyage"
  get "depannage-climatisation", to: "pages#depannage"
  get "climatisation-reversible-pompe-a-chaleur", to: "pages#clim_pompe_a_chaleur"
  get "realisation-climatisation", to: "pages#realisation"

  resources :contacts, only: [:new, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  # attribute :first_name, validate: true, length: { minimum: 2 }
  attribute :last_name, validate: true, length: { minimum: 2 }
  attribute :phone_number, validate: true, length: { minimum: 10 }
  attribute :city, validate: true
  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :message, validate: true, length: { minimum: 10 }
  attribute :nickname, captcha: true

  def headers
    { subject: "Formulaire de contact",
      to: Rails.application.credentials.dig(:gmail_smtp, :email_receiver),
      from: %("#{last_name}" <#{email}>) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def default_url_options
  #   { host: ENV["DOMAIN"] || "localhost:3000" }
  # end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    require 'mail_form'
    def new
      @contact = Contact.new
    end

    def create
      @contact = Contact.new(contacts_params)
      @contact.request = request
      if @contact.deliver
        redirect_to new_contact_path, notice: "Message envoyé!"
        # flash[:message] = "Message envoyé!"
      else
        # flash.now[:error] = "Impossible d'envoyer le message, veuillez remplir tous les champs requis!"
        redirect_to new_contact_path, notice: "Impossible d'envoyer le message, veuillez remplir tous les champs requis!"
        # render :new, status: :unprocessable_entity
      end
    end

    private

    def contacts_params
      params.require(:contact).permit(:last_name, :email, :city, :phone_number, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="contact" id="contact">
    <div class="contact-banner">
        <div class="contact-banner-text">
            <h2>DAVID CLIM À FRÉJUS</h2>
            <h2>NOUS SOMMES À VOTRE ÉCOUTE</h2>
        </div>
        <div class="contact-banner-text-line">
            <p>_______</p>
        </div>
        <%# <div class="contact-banner-text required-field-text">
            <p><em>Tous les champs sont obligatoires</em></p>
        </div> %>
    </div>
    <div class="contact-background">
    </div>
      <div class="contact-element">
        <div class="contact-text">
            <%# <div class="contact-text-description"> %>
                <h4>CONTACT &</h4>
                <h2>Infos pratiques</h2>
                <%# <p>Que vous soyez un <strong>particulier</strong> ou une <strong>entreprise</strong>, si vous avez un projet en tête (qu'il s'agisse d'une étude, d'un devis, d'une prise de rendez-vous, ou autre), l'équipe de David Clim est là pour vous accompagner. <br>Nous sommes votre partenaire de confiance pour tous vos besoins en <strong>climatisation</strong>, que ce soit pour <strong>l'installation, le dépannage, la maintenance, ou même le nettoyage</strong>, dans la région de Fréjus / Saint-Raphaël et ses environs.</p> %>
                <%# <p>Notre priorité est de vous offrir un <strong>confort thermique optimal</strong> ainsi que des solutions qui favorisent <strong>l'économie d'énergie</strong>.</p> %>
                <p>Vous êtes un <strong>particulier</strong> ou une <strong>entreprise</strong> et vous souhaitez <strong>échanger sur votre projet</strong> (étude, devis, RDV, ou autre…)?</p>
                <p>David Clim vous accompagne pour tous vos projets de climatisation d'<strong>installation</strong>, de <strong>dépannage</strong>, de <strong>maintenance</strong> ou encore de <strong>nettoyage</strong> dans la région de Fréjus / Saint-Raphaël et ses environs.</p>
                <p>Merci de compléter ce formulaire afin que nous puissions répondre à votre demande et vous recontacter.</p>
            <%# </div> %>
            <%# <div class="contact-text-information"> %>
                <p><strong>Vous pouvez aussi nous contacter par téléphone ou par e-mail:</strong></p>
                <p><i class="fa-solid fa-phone" style="color: #2576ce;"></i><span style="padding-left: 14px;">06 11 96 44 86</span></p>
                <p><i class="fa-solid fa-envelope" style="color: #2576ce;"></i><span style="padding-left: 14px;">contact@davidclim.fr</span></p>
            <%# </div> %>
        </div>
        <div class="contact-form">
            <%= simple_form_for @contact do |form| %>

                <% if @contact.errors.any? %>
                    <div id="error_explanation" class="bg-rose-200 pt-3 pb-1 mb-4 px-4 rounded-md">
                        <div class="font-bold text-rose-700 text-sm pb-4"><%= pluralize(@contact.errors.count, "error") %> prohibited this page from being saved:</div>

                        <ul class="pb-0 mb-0">
                            <% @contact.errors.each do |error| %>
                                <li class="text-rose-600 pl-4 text-sm"><%= error.full_message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>


                <div class="field">
                    <div class="field_contact1">
                      <div class="field_last_name">
                        <%# <%= form.label :"Nom *" %>
                        <%= form.text_field :last_name, placeholder: 'Nom' %>
                      </div>

                      <div class="field_email">
                          <%# <%= form.label :"email *" %>
                          <%= form.email_field :email, placeholder: 'Adresse e-mail'%>
                      </div>
                    </div>

                    <div class="field_contact2">
                      <div class="field_phone_number">
                          <%# <%= form.label :"Téléphone *" %>
                          <%= form.text_field :phone_number, placeholder: 'N° de téléphone' %>
                      </div>

                      <div class="field_city">
                          <%# <%= form.label :"Ville *" %>
                          <%= form.text_field :city, placeholder: 'Ville' %>
                      </div>
                    </div>

                    <div class="field_content" >
                        <%# <%= form.label :"Rédigez votre message ici *" %>
                        <%= form.text_area :message, placeholder: 'Rédigez votre message ici', rows: "6" %>
                    </div>

                    <div class="hidden d-none">
                        <%= form.label :nickname %>
                        <%= form.text_field :nickname %>
                    </div>

                    <div class="actions flex justify-end">
                        <p><em>Tous les champs sont obligatoires.</em></p>
                        <%=form.submit "Envoyer  → ", class: "btn-contact" %>
                    </div>
                </div>
            <% end %>
        </div>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>David Clim</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("favicon.png") %>

    <%# <title><%= @meta_title ></title> %>
    <%# <meta name="description" content="<%= @meta_description >"> %>

    <%# font %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;600;700&family=Nunito:wght@300&display=swap" rel="stylesheet">

    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# <%= javascript_importmap_tags %>
    <%# <script async src="https://ga.jspm.io/npm:es-module-shims@1.6.3/dist/es-module-shims.js"></script> %>
    <%# <script type="importmap">
      {
        "imports": {
          "application": "/javascript/application.js",
          "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js",
          "sweetalert2": "https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/+esm"
        }
      }
    </script> %>
  </head>

  <body>
  <%# <%= render "shared/title" %>
  <%= render "shared/navbar" %>
    <%= yield %>
  <%= render "shared/footer" %>
  <%= render "shared/footer_legal" %>

  <%# <script src="/app/javascript/application.js" type="module"></script> %>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </body>
</html>

app/views/pages/depannage.html.erb
<div class="container depannage">
    <div class="introduction-section">
        <div class="title-section ">
            <h1>Dépannage urgent et réparation de climatisation</h1>
            <p>_______</p>
            <%# <div id="emergency"> %>
                    <%= link_to "URGENCE DÉPANNAGE", "tel:+330611964486", class: "emergency" %>
                <%# </div> %>
        </div>
        <div class="text-section">
          <p>Les <strong>pannes</strong> de climatisation peuvent <strong>survenir et perturber</strong> votre confort <strong>à tout moment</strong>.</p>
          <p>Chez DAVID CLIM, nous comprenons l'urgence de ces situations. Bénéficiez de notre <strong>service de dépannage</strong> de climatisation, pour vous aider à maintenir un climat intérieur confortable toute l'année.</p>
<%# <p>Les pannes de climatisation peuvent survenir à tout moment, et nous comprenons à quel point cela peut être inconfortable. Notre équipe d'intervention rapide est disponible pour résoudre rapidement tout problème de climatisation que vous pourriez rencontrer. Que ce soit une panne de refroidissement, un problème de circulation d'air ou tout autre dysfonctionnement, nous sommes là pour vous aider à retrouver le confort rapidement. %>

<%# Chez [Nom de votre entreprise], nous mettons l'accent sur la qualité du service, la fiabilité et la satisfaction du client. Notre équipe est formée pour traiter toutes les marques et tous les modèles de climatisation, et nous utilisons les dernières technologies pour garantir des résultats exceptionnels. N'hésitez pas à nous contacter pour tous vos besoins en climatisation. Nous sommes là pour vous aider à maintenir un climat intérieur confortable toute l'année.</p> %>

        </div>
    </div>
</div>
<div class="container depannage-content">
<h1>Les 8 Problèmes Courants de Climatisation : Causes et Solutions </h1>


<h4>Rencontrez-vous des problèmes avec votre climatiseur ? Identifiez les signaux de dysfonctionnement en examinant les causes de la panne. Découvrez les solutions de dépannage proposées DAVID CLIM.</h4>

<p>Défaillance de l'Unité Intérieure : Si votre unité intérieure ne refroidit ni ne réchauffe, cela peut être dû à une obstruction de l'entrée ou de la sortie d'air. Nettoyez les conduits et redémarrez l'appareil. Si le problème persiste, envisagez de reprogrammer votre climatiseur. En cas d'échec, consultez des professionnels expérimentés en climatisation.</p>
<p>Fuite du Climatiseur : Une fuite d'eau peut indiquer un problème de condensation. Videz le bac à condensats, nettoyez-le, et assurez-vous de l'étanchéité. En cas de persistance du problème, une fuite de fluide frigorigène pourrait être en cause, nécessitant une intervention professionnelle urgente.</p>
<p>Formation de Givre : Si votre climatiseur gèle, éteignez-le, laissez-le dégeler, puis nettoyez ou remplacez les filtres. Si le problème persiste, une fuite ou un réglage de température défectueux pourraient être en cause, nécessitant l'intervention d'un professionnel.</p>
<p>Bruit Anormal du Climatiseur : Les bruits inhabituels peuvent indiquer divers problèmes, depuis une simple surchauffe jusqu'à des vis mal fixées. Consultez le manuel du fabricant pour l'entretien des filtres. Si le bruit persiste, faites appel à un frigoriste pour un diagnostic professionnel.</p>

<p>Mauvaises Odeurs du Climatiseur : Les mauvaises odeurs peuvent résulter de bactéries et de moisissures. Un entretien régulier avec un désinfectant est recommandé. N'oubliez pas de changer le filtre à charbon actif une à deux fois par an. Si les odeurs persistent, consultez un professionnel.</p>
<p>Arrêt Inopiné du Climatiseur : Des arrêts soudains peuvent être dus à une surtension. Branchez votre climatiseur sur un circuit relié à la terre. Si le problème persiste, nettoyez les filtres et assurez-vous que rien n'obstrue les sorties d'air extérieures.</p>
<p>Voyants Éteints ou Clignotants : Des voyants électroniques défaillants indiquent souvent un problème d'alimentation électrique. Vérifiez le disjoncteur, le fusible et le cordon d'alimentation. Si la panne persiste, consultez un professionnel pour la réparation ou le remplacement des équipements.</p>
<p>Défaillance de la Télécommande : Si la télécommande ne fonctionne plus, vérifiez les piles (pour une télécommande infrarouge), le cordon et le panneau de commande (pour une télécommande filaire), ou la batterie et la connexion au réseau (pour une télécommande Wi-Fi). Si nécessaire, remplacez la télécommande.</p>
<p>Assurez-vous de respecter les recommandations du fabricant pour un entretien régulier de votre climatiseur.</p>
</div>
<%= render "shared/partners" %>
<%= render 'shared/btn_footer_contact' %>

app/views/pages/home.html.erb
<div class="banner">
    <%# <%= image_tag "salon-clim.jpg" %>
</div>

<div class="title-homepage">
    <h2>DAVID CLIM : Spécialiste de la Climatisation dans la Région de Fréjus et Saint-Raphaël</h2>
    <p>Découvrez <strong>David Clim</strong>, votre expert en climatisation à Fréjus / Saint-Raphaël et ses environs. Notre équipe est composée de <strong>frigoristes qualifiés et diplômés d'État</strong>, prêts à répondre aux besoins des particuliers et des professionnels. Que ce soit pour <strong>l'installation, la maintenance, le nettoyage ou le dépannage</strong> de votre système de climatisation, David Clim est là pour vous servir, offrant des solutions fiables et efficaces.</p>
    <%# <p><strong>David Clim</strong> est une entreprise spécialisée dans la climatisation. Notre équipe de <strong>frigoristes diplômés d’État</strong> intervient auprès des particuliers comme des professionnels basés sur Fréjus / Saint-Raphaël et ses alentours. Qu’il s’agisse de <strong>l’installation, de la maintenance, du nettoyage ou du dépannage de votre climatisation</strong>, David Clim est apte à intervenir chez vous.</p> %>
</div>

<div class="card-homepage">
    <div class="box_one">
        <div class="card_one">
            <div class="img-homepage">
                <%= image_tag "snowflake-white.png" %>
            </div>
            <div class="text-homepage">
                <p>Notre équipe est réactive et effectue un travail particulièrement minutieux. Notre engagement envers un rapport qualité/prix avantageux garantit une satisfaction client inégalée.</p>
                <p>Vous vous demandez probablement ce qui nous distingue de nos concurrents ? Notre métier consiste à vous fournir des conseils personnalisés et à vous accompagner dans toutes les étapes de votre projet.</p>
                <%# <p>Vous vous demandez sûrement ce qui nous différencie de nos concurrents ? C’est notre métier de vous conseiller, de vous accompagner dans l’élaboration de votre projet, en venant vous rendre visite gratuitement.</p> %>
            </div>
        </div>
        <div class="card_two">
            <%= image_tag "air-conditioner-1.png" %>
        </div>
        <div class="card_three">
            <%= image_tag "air-conditioner-2.png" %>
        </div>
        <div class="card_four">
            <div class="img-homepage">
                <%= image_tag "air-conditioner-white.png" %>
            </div>
            <div class="text-homepage">
                <p>Lors de cette première rencontre, nous établissont une étude sur la concrétisation de votre projet de climatisation. Ainsi, vous restez maître de vos envies, tout en ayant une analyse climatique professionnelle sur laquelle vous appuyer.</p>
                <p>De cette manière, nous garantissons un environnement à faible consommation d'énergie grâce à DAVID CLIM, pour une atmosphère intérieure idéale !</p>
            </div>
        </div>
    </div>
</div>

<div class="block-quality">
    <div class="text-quality">
        <h2>La qualité David Clim</h2>
    </div>
    <div class="container medal">
        <div class="location">
            <%= image_tag "medal-location.png" %>
            <p>Proche de chez vous</p>
        </div>
        <div class="estimation">
            <%= image_tag "medal-estimation.png" %>
            <p>Devis gratuit</p>
        </div>
        <div class="car">
            <%= image_tag "medal-car.png" %>
            <p>Prêt à intervenir</p>
        </div>
        <div class="warranty">
            <%= image_tag "medal-warranty.png" %>
            <p>Assurance décennale</p>
        </div>
        <div class="sav">
            <%= image_tag "medal-sav.png" %>
            <p>Un S.A.V. rapide</p>
        </div>
        <div class="maintenance">
            <%= image_tag "medal-maintenance.png" %>
            <p>Un service dédié à l'entretien et au dépannage</p>
        </div>
    </div>
</div>
<div class="map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2897.3250171319096!2d6.731809203459973!3d43.432927492406215!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12cebd4e5b347a01%3A0x78f59d48472caffe!2sPlace%20Camille%20Formig%C3%A9%2C%2083600%20Fr%C3%A9jus!5e0!3m2!1sfr!2sfr!4v1690479450216!5m2!1sfr!2sfr" width="100%" height="480" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  <%# <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1cTlbvOA32850mI4Ke42Avg_1lMqCYWE&ehbc=2E312F" width="100%" height="480"></iframe> %>
</div>


<%= render 'shared/partners' %>
<%= render 'shared/btn_footer_contact' %>

app/views/pages/maintenance_nettoyage.html.erb
<div class="maintenance-banner">
    <div class="container" >
        <div class="introduction-section">
            <div class="title-section">
                <h1>Maintenance & Nettoyage</h1>
                <p>_______</p>
                <h1>David Clim : L'entretien idéal pour votre climatiseur</h1>
            </div>
            <div class="text-section">
                <%# <p>Pour maintenir votre climatisation en parfait état de fonctionnement, une maintenance régulière est essentiel pour prolonger sa durée de vie, améliorer son efficacité énergétique et garantir un air intérieur de qualité.</p> %>
                <%# <p>Faire entretenir sa climatisation par un <strong>professionnel</strong> est conseillé <strong>une fois par an</strong>. </p> %>
                <%# <p>David Clim propose des services d'entretien pour les climatiseurs résidentiels et locaux professionnels situés à Fréjus / Saint-Raphaël et ses alentours.</p> %>
                <%# <p>Nos techniciens effectuent des inspections et des ajustements pour garantir que votre système fonctionne de manière efficace, vous évitez également les risques de <strong>surconsommation d’électricité</strong> et <strong>d’éventuelles pannes</strong>. Profitez dès maintenant de nos <strong>contrats d’entretien</strong>.</p> %>
                <p>Pour maintenir votre climatisation en excellent état de fonctionnement, il est essentiel d'effectuer une maintenance régulière. Cela vous permettra de prolonger la durée de vie de votre système, d'améliorer son efficacité énergétique et de garantir une qualité d'air intérieur optimale.</p>
                <p>Il est vivement recommandé de faire entretenir votre climatisation par un <strong>professionnel</strong> au moins <strong>une fois par an</strong>.</p>
                <p>À Fréjus / Saint-Raphaël et dans les environs, David Clim propose des services d'entretien pour les climatiseurs résidentiels et les locaux professionnels. Nos techniciens effectuent des inspections approfondies et des ajustements pour assurer le bon fonctionnement de votre système. <br>Cela vous permettra non seulement d'éviter une <strong>surconsommation d'électricité</strong>, mais aussi de réduire les risques de <strong>pannes imprévues</strong>. Découvrez dès maintenant nos <strong>contrats d'entretien</strong> conçus pour répondre à vos besoins.</p>
            </div>
        </div>
    </div>
</div>


<div class="nettoyage">
    <%= render 'shared/jet_timeline_list' %>
</div>
<%# <p>Pourquoi faire entretenir votre climatisation?</p>
<p>l'entretien régulier de votre climatisation est essentiel pour maximiser son efficacité énergétique, prolonger sa durée de vie, maintenir la qualité de l'air intérieur, assurer votre confort et éviter des dépenses inutiles en réparations. Il est recommandé de faire appel à un professionnel qualifié pour effectuer l'entretien de votre climatisation conformément aux recommandations du fabricant.</p>
<p>L'entretien régulier de votre climatiseur présente de nombreux avantages. Tout d'abord, il garantit un fonctionnement optimal de votre appareil, ce qui se traduit par une performance accrue et une efficacité énergétique améliorée. Cela signifie que votre climatiseur refroidira plus rapidement et consommera moins d'énergie, ce qui se traduira par des factures d'électricité plus faibles.</p>
<p>De plus, l'entretien préventif de votre climatiseur permet de prolonger sa durée de vie. En identifiant et en corrigeant les problèmes potentiels avant qu'ils ne deviennent graves, vous éviterez des réparations coûteuses et prolongerez la vie de votre climatiseur.</p> %>
<div class="cleaning-box">
    <div class="cleaning-section">
                <%# <%= image_tag "nettoyage-clim-haute-pression.jpeg" %>
        <div class="container " >
            <div class="introduction-cleaning">
                <div class="text-cleaning">
                    <h1>Nettoyage haute pression</h1>
                    <span>_______</span>
                    <%# <h1>Entretenir votre climatiseur par David Clim</h1> %>
                <%# </div>
                <div class="text-cleaning"> %>
                    <p>Optimisez la performance de votre climatisation grâce à notre service de nettoyage haute pression. Notre équipe élimine efficacement les impuretés, garantissant un air frais et sain. <strong>Améliorez l'efficacité énergétique</strong> de votre système, prolongez sa <strong>durée de vie</strong> et respirez un air plus pur. Profitez d'un climat intérieur optimal avec notre service de nettoyage haute pression climatisation.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/btn_footer_contact' %>
<%= render "shared/partners" %>

app/views/pages/realisation.html.erb
<div class="banner-realisation">
  <div class="container">
    <h3>DAVID CLIM</h3>
    <h1>NOS RÉALISATIONS</h1>
  </div>
</div>

<%= render 'shared/card_realisation' %>
<%= render 'shared/btn_footer_contact' %>

app/views/shared/_btn_footer_contact.html.erb
<div class="contact-btn-choice">
    <p>Un projet, un devis, une maintenance, un RDV, un dépannage ?</p>
    <%= link_to "Contactez nous", new_contact_path, class: "button type1" %>
</div>

app/views/shared/_footer.html.erb
<div class="footer" id="noustrouver">
  <%# <div class="element-information"> %>
    <div class="footer-element footer-links">
        <div class="footer-title">
            <h3>Nos services</h3>
        </div>
        <div class="footer-link">
            <ul>
                <li><i class="fa-solid fa-circle-chevron-right" style="color: #2576ce;"></i><%= link_to "Installation", installation_climatisation_path, style: "padding-left: 14px;" %></li>
                <li><i class="fa-solid fa-circle-chevron-right" style="color: #2576ce;"></i><%= link_to "Maintenance", maintenance_nettoyage_climatisation_path, style: "padding-left: 14px;" %></li>
                <li><i class="fa-solid fa-circle-chevron-right" style="color: #2576ce;"></i><%= link_to "Nettoyage", maintenance_nettoyage_climatisation_path, style: "padding-left: 14px;" %></li>
                <li><i class="fa-solid fa-circle-chevron-right" style="color: #2576ce;"></i><%= link_to "Dépannage", depannage_climatisation_path, style: "padding-left: 14px;" %></li>
            </ul>
        </div>
    </div>
    <div class="footer-element footer-text">
        <div class="footer-title">
            <h3>Contact</h3>
        </div>
        <div class="footer-information">
            <ul>
              <li><i class="fa-solid fa-phone" style="color: #2576ce;"></i><span style="padding-left: 14px;">06 11 96 44 86</span></li>
              <li><i class="fa-solid fa-envelope" style="color: #2576ce;"></i><span style="padding-left: 14px;">contact@davidclim.fr</span></li>
              <li><i class="fa-solid fa-clock" style="color: #2576ce;"></i><span style="padding-left: 14px;">Lundi - Vendredi : 8h30/ 19h</span></li>
            </ul>
        </div>
    </div>
  <div class="footer-element logo-footer">
    <%= image_tag "logo_name.png" %>
    <%# <p>Spécialisé dans la climatisation, David Clim intervient auprès des particuliers et professionnels. Nous intervenons à Fréjus / Saint-Raphaël et alentours.</p> %>
    <p>David Clim : Votre Expert en Climatisation. <br>Nous basés à Fréjus et intervenons dans le Var et les Alpes-Maritimes</p>
  </div>
</div>
  <%# </div> %>
  <%# <div class="footer-element social-icons">
    <a href='https://www.facebook.com/atoutjardins' target='_blank'><i class="fa-brands fa-square-facebook fa-lg" style="color: #ffffff;"></i></a>

  </div> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
        <div class="info-contact">
            <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "logo_name.png" %>
            <% end %>
            <div class="info">
                <div class="phone-number">
                    <p>06 11 96 44 86</p>
                </div>
                <%# <div class="quotes"> %>
                    <%= link_to "Demandez un devis", new_contact_path, class: "quotes" %>
                <%# </div> %>
            </div>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto active">
                <li class="nav-item ">
                    <%= link_to "Accueil", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item ">
                    <%= link_to "Installation", installation_climatisation_path, class: "nav-link" %>
                </li>
                <li class="nav-item ">
                    <%= link_to "Maintenance <br /> & Nettoyage".html_safe, maintenance_nettoyage_climatisation_path, class: "nav-link" %>
                </li>
                <li class="nav-item ">
                    <%= link_to "Dépannage".html_safe, depannage_climatisation_path, class: "nav-link" %>
                </li>
                <%# <li class="nav-item">
                    <%= link_to "Climatisation réversible <br />/ Pompe à chaleur".html_safe, climatisation_reversible_pompe_a_chaleur_path, class: "nav-link" %>
                <%# </li> %>
                <li class="nav-item ">
                    <%= link_to "Réalisations", realisation_climatisation_path, class: "nav-link" %>
                </li>
                <li class="nav-item ">
                    <%= link_to "Contact", new_contact_path, class: "nav-link" %>
                </li>
            </ul>
        </div>
    </div>
</div>